---
- name: deploy latest regional rail explorer on lightsail
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: get latest github repo
      git:
        repo: https://github.com/transitmatters/regional-rail-explorer.git
        dest: /home/ubuntu/regional-rail-explorer
        force: yes

    - name: copy supervisor config file
      copy:
        src: /home/ubuntu/regional-rail-explorer/devops/regional-rail-explorer-supervisor.conf
        dest: /etc/supervisor/conf.d/
        remote_src: yes

    - name: copy nginx config file
      copy:
        src: /home/ubuntu/regional-rail-explorer/devops/regional-rail-explorer-nginx.conf
        dest: /etc/nginx/sites-enabled/
        remote_src: yes

    - name: restart supervisor
      service:
        name: supervisor 
        state: restarted

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes

    - name: update npm
      shell: npm update
      args:
        chdir: /home/ubuntu/regional-rail-explorer

    - name: build application with npm
      shell: npm run build
      args:
        chdir: /home/ubuntu/regional-rail-explorer
      environment:
        NODE_OPTIONS: --max-old-space-size=2048

    - name: restart regional-rail-explorer service
      shell: supervisorctl restart regional-rail-explorer
