import { JourneySegment } from "types";

export const baseline: JourneySegment[] = [
    { type: "transfer", startTime: 26100, waitDuration: 1080, transferDuration: 0 },
    {
        type: "travel",
        departureTime: 27180,
        arrivalTime: 29280,
        levelBoarding: false,
        fromStation: { name: "Salem", id: "place-ER-0168" },
        toStation: { name: "North Station", id: "place-north" },
        passedStations: [
            { time: 27660, station: { name: "Swampscott", id: "place-ER-0128" } },
            { time: 27900, station: { name: "Lynn", id: "place-ER-0115" } },
            { time: 28080, station: { name: "River Works", id: "place-ER-0099" } },
            { time: 28500, station: { name: "Chelsea", id: "place-ER-0046" } },
        ],
        routeId: "CR-Newburyport",
        routePatternId: "Newburyport",
    },
    { type: "transfer", startTime: 29280, transferDuration: 302, waitDuration: 298 },
    {
        type: "travel",
        levelBoarding: true,
        departureTime: 29880,
        arrivalTime: 30240,
        fromStation: { name: "North Station", id: "place-north" },
        toStation: { name: "Downtown Crossing", id: "place-dwnxg" },
        passedStations: [
            { time: 30000, station: { name: "Haymarket", id: "place-haecl" } },
            { time: 30120, station: { name: "State", id: "place-state" } },
        ],
        routeId: "Orange",
        routePatternId: "Orange",
    },
    { type: "transfer", startTime: 30240, transferDuration: 115, waitDuration: 5 },
    {
        type: "travel",
        departureTime: 30360,
        arrivalTime: 30480,
        levelBoarding: true,
        fromStation: { name: "Downtown Crossing", id: "place-dwnxg" },
        toStation: { name: "South Station", id: "place-sstat" },
        passedStations: [],
        routeId: "Red",
        routePatternId: "Red",
    },
    { type: "transfer", startTime: 30480, transferDuration: 162, waitDuration: 558 },
    {
        type: "travel",
        departureTime: 31200,
        arrivalTime: 31800,
        levelBoarding: false,
        fromStation: { name: "South Station", id: "place-sstat" },
        toStation: { name: "Uphams Corner", id: "place-DB-2258" },
        passedStations: [{ time: 31680, station: { name: "Newmarket", id: "place-DB-2265" } }],
        routeId: "CR-Fairmount",
        routePatternId: "Fairmount",
    },
];

export const enhanced: JourneySegment[] = [
    { type: "transfer", startTime: 26100, waitDuration: 500, transferDuration: 0 },
    {
        type: "travel",
        departureTime: 26600,
        arrivalTime: 27900,
        levelBoarding: true,
        fromStation: { name: "Salem", id: "place-ER-0168" },
        toStation: { name: "North Station", id: "place-north" },
        passedStations: [
            { time: 27660, station: { name: "Swampscott", id: "place-ER-0128" } },
            { time: 27900, station: { name: "Lynn", id: "place-ER-0115" } },
            { time: 28080, station: { name: "River Works", id: "place-ER-0099" } },
            { time: 28500, station: { name: "Chelsea", id: "place-ER-0046" } },
        ],
        routeId: "CR-Newburyport",
        routePatternId: "Newburyport",
    },
    { type: "transfer", startTime: 29280, transferDuration: 302, waitDuration: 298 },
    {
        type: "travel",
        departureTime: 28420,
        arrivalTime: 28780,
        levelBoarding: true,
        fromStation: { name: "North Station", id: "place-north" },
        toStation: { name: "Downtown Crossing", id: "place-dwnxg" },
        passedStations: [
            { time: 30000, station: { name: "Haymarket", id: "place-haecl" } },
            { time: 30120, station: { name: "State", id: "place-state" } },
        ],
        routeId: "Orange",
        routePatternId: "Orange",
    },
    { type: "transfer", startTime: 28780, transferDuration: 115, waitDuration: 5 },
    {
        type: "travel",
        levelBoarding: true,
        departureTime: 28900,
        arrivalTime: 29020,
        fromStation: { name: "Downtown Crossing", id: "place-dwnxg" },
        toStation: { name: "South Station", id: "place-sstat" },
        passedStations: [],
        routeId: "Red",
        routePatternId: "Red",
    },
    { type: "transfer", startTime: 30480, transferDuration: 162, waitDuration: 450 },
    {
        type: "travel",
        levelBoarding: true,
        departureTime: 29632,
        arrivalTime: 30052,
        fromStation: { name: "South Station", id: "place-sstat" },
        toStation: { name: "Uphams Corner", id: "place-DB-2258" },
        passedStations: [{ time: 31300, station: { name: "Newmarket", id: "place-DB-2265" } }],
        routeId: "CR-Fairmount",
        routePatternId: "Fairmout",
    },
];
