export type Station = { id: string; name: string; disabled?: true };

export const stationsByLine: Record<string, Station[]> = {
    Fairmount: [
        { id: "place-DB-0095", name: "Readville" },
        { id: "place-DB-2205", name: "Fairmount" },
        { id: "place-DB-2222", name: "Blue Hill Avenue" },
        { id: "place-DB-2230", name: "Morton Street" },
        { id: "place-DB-2240", name: "Talbot Avenue" },
        { id: "place-DB-2249", name: "Four Corners/Geneva" },
        { id: "place-DB-2258", name: "Uphams Corner" },
        { id: "place-DB-2265", name: "Newmarket" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-rr-ceylon-park", name: "Ceylon Park" },
        { id: "place-rr-river-street", name: "River Street" },
    ],
    Franklin: [
        { id: "place-FB-0303", name: "Forge Park/495" },
        { id: "place-FB-0275", name: "Franklin" },
        { id: "place-FB-0230", name: "Norfolk" },
        { id: "place-FB-0191", name: "Walpole" },
        { id: "place-FB-0166", name: "Windsor Gardens" },
        { id: "place-FB-0148", name: "Norwood Central" },
        { id: "place-FB-0143", name: "Norwood Depot" },
        { id: "place-FB-0125", name: "Islington" },
        { id: "place-FB-0118", name: "Dedham Corp Center" },
        { id: "place-FB-0109", name: "Endicott" },
        { id: "place-DB-0095", name: "Readville" },
        { id: "place-rugg", name: "Ruggles" },
        { id: "place-bbsta", name: "Back Bay" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-FS-0049", name: "Foxboro" },
        { id: "place-DB-2205", name: "Fairmount" },
        { id: "place-DB-2222", name: "Blue Hill Avenue" },
        { id: "place-DB-2230", name: "Morton Street" },
        { id: "place-DB-2240", name: "Talbot Avenue" },
        { id: "place-DB-2249", name: "Four Corners/Geneva" },
        { id: "place-DB-2258", name: "Uphams Corner" },
        { id: "place-DB-2265", name: "Newmarket" },
        { id: "place-FB-0177", name: "Plimptonville" },
        { id: "place-NEC-2203", name: "Hyde Park" },
    ],
    Silver: [
        { id: "place-chels", name: "Chelsea" },
        { id: "place-belsq", name: "Bellingham Square" },
        { id: "place-boxdt", name: "Box District" },
        { id: "place-estav", name: "Eastern Avenue" },
        { id: "place-aport", name: "Airport" },
        { id: "place-conrd", name: "Silver Line Way" },
        { id: "place-wtcst", name: "World Trade Center" },
        { id: "place-crtst", name: "Courthouse" },
        { id: "place-sstat", name: "South Station" },
    ],
    Newburyport: [
        { id: "place-GB-0353", name: "Rockport", disabled: true },
        { id: "place-GB-0316", name: "Gloucester", disabled: true },
        { id: "place-GB-0296", name: "West Gloucester", disabled: true },
        { id: "place-GB-0254", name: "Manchester", disabled: true },
        { id: "place-GB-0229", name: "Beverly Farms", disabled: true },
        { id: "place-GB-0198", name: "Montserrat", disabled: true },
        { id: "place-ER-0183", name: "Beverly" },
        { id: "place-ER-0168", name: "Salem" },
        { id: "place-ER-0128", name: "Swampscott" },
        { id: "place-ER-0115", name: "Lynn" },
        { id: "place-ER-0099", name: "River Works" },
        { id: "place-wondl", name: "Wonderland" },
        { id: "place-chels", name: "Chelsea" },
        { id: "place-north", name: "North Station" },
        { id: "place-ER-0362", name: "Newburyport" },
        { id: "place-ER-0312", name: "Rowley" },
        { id: "place-ER-0276", name: "Ipswich" },
        { id: "place-ER-0227", name: "Hamilton/Wenham" },
        { id: "place-ER-0208", name: "North Beverly" },
        { id: "place-GB-0222", name: "Prides Crossing" },
        { id: "place-rr-everett-jct", name: "S. Broadway/Everett Jct" },
        { id: "place-rr-revere-center", name: "Revere Center" },
        { id: "place-rr-south-salem", name: "South Salem" },
    ],
    Fitchburg: [
        { id: "place-FR-3338", name: "Wachusett" },
        { id: "place-FR-0494", name: "Fitchburg" },
        { id: "place-FR-0451", name: "North Leominster" },
        { id: "place-FR-0394", name: "Shirley" },
        { id: "place-FR-0361", name: "Ayer" },
        { id: "place-FR-0301", name: "Littleton/Rte 495" },
        { id: "place-FR-0253", name: "South Acton" },
        { id: "place-FR-0219", name: "West Concord" },
        { id: "place-FR-0201", name: "Concord" },
        { id: "place-FR-0167", name: "Lincoln" },
        { id: "place-FR-0137", name: "Hastings" },
        { id: "place-FR-0132", name: "Kendal Green" },
        { id: "place-FR-0115", name: "Brandeis/Roberts" },
        { id: "place-FR-0098", name: "Waltham" },
        { id: "place-FR-0074", name: "Waverley" },
        { id: "place-FR-0064", name: "Belmont" },
        { id: "place-portr", name: "Porter" },
        { id: "place-north", name: "North Station" },
        { id: "place-FR-0147", name: "Silver Hill" },
        { id: "place-rr-brickbottom", name: "Brickbottom" },
        { id: "place-rr-clematis-brook", name: "Clematis Brook/Warrendale" },
        { id: "place-rr-weston-128", name: "Weston/128" },
    ],
    Greenbush: [
        { id: "place-GRB-0276", name: "Greenbush" },
        { id: "place-GRB-0233", name: "North Scituate" },
        { id: "place-GRB-0199", name: "Cohasset" },
        { id: "place-GRB-0183", name: "Nantasket Junction" },
        { id: "place-GRB-0162", name: "West Hingham" },
        { id: "place-GRB-0146", name: "East Weymouth" },
        { id: "place-GRB-0118", name: "Weymouth Landing/East Braintree" },
        { id: "place-qnctr", name: "Quincy Center" },
        { id: "place-jfk", name: "JFK/UMass" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-rr-cohasset-center", name: "Cohasset Center" },
    ],
    Kingston: [
        { id: "place-PB-0281", name: "Halifax" },
        { id: "place-PB-0245", name: "Hanson" },
        { id: "place-PB-0212", name: "Whitman" },
        { id: "place-PB-0194", name: "Abington" },
        { id: "place-PB-0158", name: "South Weymouth" },
        { id: "place-jfk", name: "JFK/UMass" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-brntn", name: "Braintree" },
        { id: "place-qnctr", name: "Quincy Center" },
        { id: "place-PB-0356", name: "Plymouth" },
        { id: "place-rr-weymouth-col-sq", name: "Weymouth Columbian Square" },
        { id: "place-rockland-n-abington", name: "Rockland-North Abington" },
        { id: "place-kingston-jct", name: "Kingston Junction" },
        { id: "place-plymouth-center", name: "Plymouth Center" },
    ],
    Middleborough: [
        { id: "place-MM-0356", name: "Middleborough/Lakeville" },
        { id: "place-MM-0277", name: "Bridgewater" },
        { id: "place-MM-0219", name: "Campello" },
        { id: "place-MM-0200", name: "Brockton" },
        { id: "place-MM-0186", name: "Montello" },
        { id: "place-MM-0150", name: "Holbrook/Randolph" },
        { id: "place-brntn", name: "Braintree" },
        { id: "place-jfk", name: "JFK/UMass" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-qnctr", name: "Quincy Center" },
        { id: "place-rr-braintree-highlands", name: "Braintree Highlands" },
        { id: "place-rr-bridgewater-center", name: "Bridgewater Center" },
        { id: "place-rr-mboro-centre-st", name: "Middleborough Centre St" },
    ],
    Needham: [
        { id: "place-NB-0137", name: "Needham Heights" },
        { id: "place-NB-0127", name: "Needham Center" },
        { id: "place-NB-0120", name: "Needham Junction" },
        { id: "place-NB-0109", name: "Hersey" },
        { id: "place-NB-0080", name: "West Roxbury" },
        { id: "place-NB-0076", name: "Highland" },
        { id: "place-NB-0072", name: "Bellevue" },
        { id: "place-NB-0064", name: "Roslindale Village" },
        { id: "place-forhl", name: "Forest Hills" },
        { id: "place-rugg", name: "Ruggles" },
        { id: "place-bbsta", name: "Back Bay" },
        { id: "place-sstat", name: "South Station" },
    ],
    Providence: [
        { id: "place-NEC-1659", name: "Wickford Junction" },
        { id: "place-NEC-1768", name: "TF Green Airport" },
        { id: "place-NEC-1851", name: "Providence" },
        { id: "place-NEC-1919", name: "South Attleboro" },
        { id: "place-NEC-1969", name: "Attleboro" },
        { id: "place-NEC-2040", name: "Mansfield" },
        { id: "place-NEC-2108", name: "Sharon" },
        { id: "place-NEC-2139", name: "Canton Junction" },
        { id: "place-NEC-2173", name: "Route 128" },
        { id: "place-NEC-2203", name: "Hyde Park" },
        { id: "place-rugg", name: "Ruggles" },
        { id: "place-bbsta", name: "Back Bay" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-SB-0189", name: "Stoughton" },
        { id: "place-SB-0156", name: "Canton Center" },
        { id: "place-rr-pawtucket", name: "Pawtucket" },
    ],
    Lowell: [
        { id: "place-north", name: "North Station" },
        { id: "place-rr-tufts-university", name: "Tufts University" },
        { id: "place-NHRML-0055", name: "West Medford" },
        { id: "place-NHRML-0073", name: "Wedgemere" },
        { id: "place-NHRML-0078", name: "Winchester Center" },
        { id: "place-rr-montvale-avenue", name: "Montvale Avenue" },
        { id: "place-NHRML-0116", name: "Mishawum" },
        { id: "place-NHRML-0127", name: "Anderson/Woburn" },
        { id: "place-NHRML-0152", name: "Wilmington" },
        { id: "place-NHRML-0218", name: "North Billerica" },
        { id: "place-NHRML-0254", name: "Lowell" },
        { id: "place-rr-umass-lowell", name: "UMass Lowell" },
        { id: "place-rr-rourke-bridge", name: "Rourke Bridge" },
        { id: "place-rr-willow-springs", name: "Willow Springs" },
        { id: "place-rr-nashua", name: "Nashua" },
        { id: "place-rr-merrimack", name: "Merrimack" },
        { id: "place-rr-manchester-center", name: "Manchester Center" },
    ],
    Haverhill: [
        { id: "place-WR-0329", name: "Haverhill" },
        { id: "place-WR-0325", name: "Bradford" },
        { id: "place-WR-0264", name: "Lawrence" },
        { id: "place-WR-0228", name: "Andover" },
        { id: "place-WR-0205", name: "Ballardvale" },
        { id: "place-north", name: "North Station" },
        { id: "place-WR-0163", name: "North Wilmington" },
        { id: "place-WR-0120", name: "Reading" },
        { id: "place-WR-0099", name: "Wakefield" },
        { id: "place-WR-0085", name: "Greenwood" },
        { id: "place-WR-0075", name: "Melrose Highlands" },
        { id: "place-WR-0067", name: "Melrose Cedar Park" },
        { id: "place-WR-0062", name: "Wyoming Hill" },
        { id: "place-mlmnl", name: "Malden Center" },
        { id: "place-sull", name: "Sullivan Square" },
    ],
    Worcester: [
        { id: "place-sstat", name: "South Station" },
        { id: "place-bbsta", name: "Back Bay" },
        { id: "place-WML-0025", name: "Lansdowne" },
        { id: "place-WML-0035", name: "Boston Landing" },
        { id: "place-WML-0081", name: "Newtonville" },
        { id: "place-WML-0091", name: "West Newton" },
        { id: "place-WML-0102", name: "Auburndale" },
        { id: "place-WML-0125", name: "Wellesley Farms" },
        { id: "place-WML-0135", name: "Wellesley Hills" },
        { id: "place-WML-0147", name: "Wellesley Square" },
        { id: "place-WML-0177", name: "Natick Center" },
        { id: "place-WML-0199", name: "West Natick" },
        { id: "place-WML-0214", name: "Framingham" },
        { id: "place-WML-0252", name: "Ashland" },
        { id: "place-WML-0274", name: "Southborough" },
        { id: "place-WML-0340", name: "Westborough" },
        { id: "place-WML-0364", name: "Grafton" },
        { id: "place-WML-0442", name: "Worcester" },
        { id: "place-rr-newton-corner", name: "Newton Corner" },
        { id: "place-rr-west-station", name: "West Station" },
    ],
    Red: [
        { id: "place-alfcl", name: "Alewife" },
        { id: "place-davis", name: "Davis" },
        { id: "place-portr", name: "Porter" },
        { id: "place-harsq", name: "Harvard" },
        { id: "place-cntsq", name: "Central" },
        { id: "place-knncl", name: "Kendall/MIT" },
        { id: "place-chmnl", name: "Charles/MGH" },
        { id: "place-pktrm", name: "Park Street" },
        { id: "place-dwnxg", name: "Downtown Crossing" },
        { id: "place-sstat", name: "South Station" },
        { id: "place-brdwy", name: "Broadway" },
        { id: "place-andrw", name: "Andrew" },
        { id: "place-jfk", name: "JFK/UMass" },
        { id: "place-shmnl", name: "Savin Hill" },
        { id: "place-fldcr", name: "Fields Corner" },
        { id: "place-smmnl", name: "Shawmut" },
        { id: "place-asmnl", name: "Ashmont" },
        { id: "place-nqncy", name: "North Quincy" },
        { id: "place-wlsta", name: "Wollaston" },
        { id: "place-qnctr", name: "Quincy Center" },
        { id: "place-qamnl", name: "Quincy Adams" },
        { id: "place-brntn", name: "Braintree" },
    ],
    Green: [
        { id: "place-lake", name: "Boston College" },
        { id: "place-sougr", name: "South Street" },
        { id: "place-chill", name: "Chestnut Hill Avenue" },
        { id: "place-chswk", name: "Chiswick Road" },
        { id: "place-sthld", name: "Sutherland Road" },
        { id: "place-wascm", name: "Washington Street" },
        { id: "place-alsgr", name: "Allston Street" },
        { id: "place-wrnst", name: "Warren Street" },
        { id: "place-grigg", name: "Griggs Street" },
        { id: "place-harvd", name: "Harvard Avenue" },
        { id: "place-brico", name: "Packards Corner" },
        { id: "place-babck", name: "Babcock Street" },
        { id: "place-plsgr", name: "Pleasant Street" },
        { id: "place-buwst", name: "Boston University West" },
        { id: "place-stplb", name: "Saint Paul Street" },
        { id: "place-bucen", name: "Boston University Central" },
        { id: "place-buest", name: "Boston University East" },
        { id: "place-bland", name: "Blandford Street" },
        { id: "place-kencl", name: "Kenmore" },
        { id: "place-hymnl", name: "Hynes Convention Center" },
        { id: "place-coecl", name: "Copley" },
        { id: "place-armnl", name: "Arlington" },
        { id: "place-boyls", name: "Boylston" },
        { id: "place-pktrm", name: "Park Street" },
        { id: "place-gover", name: "Government Center" },
        { id: "place-haecl", name: "Haymarket" },
        { id: "place-north", name: "North Station" },
        { id: "place-spmnl", name: "Science Park/West End" },
        { id: "place-lech", name: "Lechmere" },
        { id: "place-unsqu", name: "Union Square" },
        { id: "place-clmnl", name: "Cleveland Circle" },
        { id: "place-engav", name: "Englewood Avenue" },
        { id: "place-denrd", name: "Dean Road" },
        { id: "place-tapst", name: "Tappan Street" },
        { id: "place-bcnwa", name: "Washington Square" },
        { id: "place-bndhl", name: "Brandon Hall" },
        { id: "place-fbkst", name: "Fairbanks Street" },
        { id: "place-sumav", name: "Summit Avenue" },
        { id: "place-cool", name: "Coolidge Corner" },
        { id: "place-stpul", name: "Saint Paul Street" },
        { id: "place-kntst", name: "Kent Street" },
        { id: "place-hwsst", name: "Hawes Street" },
        { id: "place-smary", name: "Saint Marys Street" },
        { id: "place-river", name: "Riverside" },
        { id: "place-woodl", name: "Woodland" },
        { id: "place-waban", name: "Waban" },
        { id: "place-eliot", name: "Eliot" },
        { id: "place-newtn", name: "Newton Highlands" },
        { id: "place-newto", name: "Newton Centre" },
        { id: "place-chhil", name: "Chestnut Hill" },
        { id: "place-rsmnl", name: "Reservoir" },
        { id: "place-bcnfd", name: "Beaconsfield" },
        { id: "place-brkhl", name: "Brookline Hills" },
        { id: "place-bvmnl", name: "Brookline Village" },
        { id: "place-longw", name: "Longwood" },
        { id: "place-fenwy", name: "Fenway" },
        { id: "place-hsmnl", name: "Heath Street" },
        { id: "place-bckhl", name: "Back of the Hill" },
        { id: "place-rvrwy", name: "Riverway" },
        { id: "place-mispk", name: "Mission Park" },
        { id: "place-brmnl", name: "Brigham Circle" },
        { id: "place-fenwd", name: "Fenwood Road" },
        { id: "place-lngmd", name: "Longwood Medical Area" },
        { id: "place-mfa", name: "Museum of Fine Arts" },
        { id: "place-nuniv", name: "Northeastern University" },
        { id: "place-symcl", name: "Symphony" },
        { id: "place-prmnl", name: "Prudential" },
    ],
    Blue: [
        { id: "place-orhte", name: "Orient Heights" },
        { id: "place-wimnl", name: "Wood Island" },
        { id: "place-aport", name: "Airport" },
        { id: "place-mvbcl", name: "Maverick" },
        { id: "place-aqucl", name: "Aquarium" },
        { id: "place-state", name: "State" },
        { id: "place-gover", name: "Government Center" },
        { id: "place-bomnl", name: "Bowdoin" },
        { id: "place-wondl", name: "Wonderland" },
        { id: "place-rbmnl", name: "Revere Beach" },
        { id: "place-bmmnl", name: "Beachmont" },
        { id: "place-sdmnl", name: "Suffolk Downs" },
    ],
    Orange: [
        { id: "place-ogmnl", name: "Oak Grove" },
        { id: "place-mlmnl", name: "Malden Center" },
        { id: "place-welln", name: "Wellington" },
        { id: "place-astao", name: "Assembly" },
        { id: "place-sull", name: "Sullivan Square" },
        { id: "place-ccmnl", name: "Community College" },
        { id: "place-north", name: "North Station" },
        { id: "place-haecl", name: "Haymarket" },
        { id: "place-state", name: "State" },
        { id: "place-dwnxg", name: "Downtown Crossing" },
        { id: "place-chncl", name: "Chinatown" },
        { id: "place-tumnl", name: "Tufts Medical Center" },
        { id: "place-bbsta", name: "Back Bay" },
        { id: "place-masta", name: "Massachusetts Avenue" },
        { id: "place-rugg", name: "Ruggles" },
        { id: "place-rcmnl", name: "Roxbury Crossing" },
        { id: "place-jaksn", name: "Jackson Square" },
        { id: "place-sbmnl", name: "Stony Brook" },
        { id: "place-grnst", name: "Green Street" },
        { id: "place-forhl", name: "Forest Hills" },
    ],
};

const indexStationsByProperty = (property: "id" | "name") => {
    return Object.values(stationsByLine).reduce(
        (allStations: Record<string, Station>, lineStations) => {
            lineStations.forEach((station) => {
                const propertyValue = station[property];
                if (!allStations[propertyValue]) {
                    allStations[propertyValue] = station;
                }
            });
            return allStations;
        },
        {}
    );
};

export const stationsById = indexStationsByProperty("id");
export const stationsByName = indexStationsByProperty("name");

export const getLinkToStation = (station: { id: string }) => {
    return `/station/${station.id}`;
};

const alwaysInfillStations = new Set([
    "place-rr-everett-jct",
    "place-rr-revere-center",
    "place-rr-south-salem",
    "place-rr-tufts-university",
    "place-rr-montvale-avenue",
    "place-rr-umass-lowell",
    "place-rr-rourke-bridge",
    "place-rr-willow-springs",
    "place-rr-nashua",
    "place-rr-merrimack",
    "place-rr-manchester-center",
    "place-rr-brickbottom",
    "place-rr-clematis-brook",
    "place-rr-weston-128",
    "place-rr-ceylon-park",
    "place-rr-river-street",
    "place-rr-west-station",
    "place-rr-newton-corner",
    "place-rr-pawtucket",
    "place-rr-hingham-depot",
    "place-rr-cohasset-center",
    "place-rr-braintree-highlands",
    "place-rr-bridgewater-center",
    "place-rr-mboro-centre-st",
    "place-rr-weymouth-col-sq",
    "place-rockland-n-abington",
    "place-kingston-jct",
    "place-plymouth-center",
]);

const infillStationsByRotue = {
    "CR-Newburyport": new Set(["place-sull"]),
    "CR-Reading": new Set(["place-sull"]),
    "CR-Fitchburg": new Set(["place-unsqu"]),
};

export const isInfillStation = (stationId: string, routeId: string) => {
    if (alwaysInfillStations.has(stationId)) {
        return true;
    }
    if (infillStationsByRotue[routeId] && infillStationsByRotue[routeId].has(stationId)) {
        return true;
    }
    return false;
};
