name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node ${{ matrix.node-version }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up CI Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Check if package-lock.json is up to date
        run: |
          npx --yes package-lock-utd@1.1.0
      - name: Install app dependencies
        run: npm ci
      - name: Fully build application
        run: npm run build
